mutation accountDisableNotificationCategory(
  $input: AccountDisableNotificationCategoryInputAlt!
) {
  accountDisableNotificationCategoryAlt(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
