mutation accountEnableNotificationChannel(
  $input: AccountEnableNotificationChannelInputAlt!
) {
  accountEnableNotificationChannelAlt(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
