mutation accountDisableNotificationChannel($input: AccountDisableNotificationChannelInputAlt!) {
  accountDisableNotificationChannelAlt(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
