mutation accountEnableNotificationCategory(
  $input: AccountEnableNotificationCategoryInputAlt!
) {
  accountEnableNotificationCategoryAlt(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
