query apiKeys {
  me {
    defaultAccount {
      id
    }
    authorization {
      scopes
    }
    apiKeys {
      id
      name
      revoked
      createdAt
      expiresAt
      readOnly
      scopes
    }
  }
}
