query apiKeys {
  me {
    defaultAccount {
      id
    }
    permissions {
      read
      write
      receive
    }
    apiKeys {
      id
      name
      revoked
      createdAt
      expiresAt
      readOnly
      scopes
    }
  }
}
