query invoicesByPartialExternalId(
  $walletId: WalletId!
  $partialExternalId: TxExternalIdSubstring!
  $first: Int
  $after: String
) {
  me {
    defaultAccount {
      id
      displayCurrency
      walletById(walletId: $walletId) {
        id
        invoicesByPartialExternalId(
          partialExternalId: $partialExternalId
          first: $first
          after: $after
        ) {
          ...InvoiceList
        }
      }
    }
  }
}

fragment InvoiceList on InvoiceConnection {
  pageInfo {
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      paymentHash
      externalId
    }
  }
}
