query listStatefulNotifications($first: Int = 2, $after: String = null) {
  me {
    id
    statefulNotifications(first: $first, after: $after) {
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        id
        body
        title
        deepLink
        acknowledgedAt
        createdAt
      }
    }
  }
}
