subscription lnInvoicePaymentStatusByPaymentRequestSubscription($input: LnInvoicePaymentStatusByPaymentRequestInput!) {
  lnInvoicePaymentStatusByPaymentRequest(input: $input) {
    errors {
      message
    }
    status
    paymentHash
    paymentRequest
  }
}
