subscription lnInvoicePaymentStatusByRequestSubscription($input: LnInvoicePaymentStatusByRequestInput!) {
  lnInvoicePaymentStatusByRequest(input: $input) {
    errors {
      message
    }
    status
    paymentHash
    paymentRequest
  }
}
