query LnInvoicePaymentStatusByPaymentRequestQuery($input: LnInvoicePaymentStatusByPaymentRequestInput!) {
  lnInvoicePaymentStatusByPaymentRequest(input: $input) {
    status
    paymentHash
    paymentRequest
  }
}
