mutation lnNoAmountInvoiceCreateOnBehalfOfRecipient(
  $input: LnNoAmountInvoiceCreateOnBehalfOfRecipientInput!
) {
  lnNoAmountInvoiceCreateOnBehalfOfRecipient(input: $input) {
    invoice {
      paymentRequest
      paymentHash
    }
    errors {
      message
    }
  }
}