mutation lnUsdInvoiceCreateOnBehalfOfRecipient(
  $input: LnUsdInvoiceCreateOnBehalfOfRecipientInput!
) {
  lnUsdInvoiceCreateOnBehalfOfRecipient(input: $input) {
    invoice {
      paymentRequest
      paymentHash
    }
    errors {
      message
    }
  }
}