mutation lnUsdInvoiceBtcDenominatedCreateOnBehalfOfRecipient(
  $input: LnUsdInvoiceBtcDenominatedCreateOnBehalfOfRecipientInput!
) {
  lnUsdInvoiceBtcDenominatedCreateOnBehalfOfRecipient(input: $input) {
    invoice {
      paymentRequest
      paymentHash
    }
    errors {
      message
    }
  }
}