query transactionsByPartialExternalId(
  $partialExternalId: TxExternalIdSubstring!
) {
  me {
    defaultAccount {
      displayCurrency
      wallets {
        __typename
        id
        walletCurrency
        transactionsByPartialExternalId(partialExternalId: $partialExternalId) {
          ...TransactionList
        }
      }
    }
  }
}

fragment TransactionList on TransactionConnection {
  pageInfo {
    hasNextPage
  }
  edges {
    cursor
    node {
      __typename
      id
      externalId
      status
      direction
      memo
      createdAt
      settlementAmount
      settlementFee
      settlementDisplayAmount
      settlementDisplayFee
      settlementDisplayCurrency
      settlementCurrency
      settlementPrice {
        base
        offset
      }
      initiationVia {
        __typename
        ... on InitiationViaIntraLedger {
          counterPartyWalletId
          counterPartyUsername
        }
        ... on InitiationViaLn {
          paymentHash
        }
        ... on InitiationViaOnChain {
          address
        }
      }
      settlementVia {
        __typename
        ... on SettlementViaIntraLedger {
          counterPartyWalletId
          counterPartyUsername
        }
        ... on SettlementViaLn {
          preImage
        }
        ... on SettlementViaOnChain {
          transactionHash
        }
      }
    }
  }
}
