mutation userUpdateUsername($input: UserUpdateUsernameInput!) {
  userUpdateUsername(input: $input) {
    errors {
      message
      __typename
    }
    user {
      id
      defaultAccount {
        username
      }
      __typename
    }
    __typename
  }
}
