apiVersion: v1
kind: Service
metadata:
  name: {{ include "price.fullname" . }}
  labels:
    {{- include "price.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "price.selectorLabels" . | nindent 4 }}
