query GetFirstTransactions($first: Int!) {
  me {
    defaultAccount {
      transactions(first: $first) {
        edges {
          node {
            settlementAmount
            settlementCurrency
            status
            settlementDisplayAmount
          }
        }
      }
    }
  }
}
