name: "Galoy Banking"

# username of the account that will be used to fund rewards
funder: "FunderWallet"

buildVersion:
  android:
    minBuildNumber: 182
    lastBuildNumber: 294
  ios:
    minBuildNumber: 182
    lastBuildNumber: 269

hedging:
  LOW_BOUND_RATIO_SHORTING: 0.95
  LOW_SAFEBOUND_RATIO_SHORTING: 0.98
# average: 0.99
  HIGH_SAFEBOUND_RATIO_SHORTING: 1
  HIGH_BOUND_RATIO_SHORTING: 1.03

# take a target leverage and safe parameter and calculate those bounding values dynamically.
  LOW_BOUND_LEVERAGE: 1.2
  LOW_SAFEBOUND_LEVERAGE: 1.8
#  // average: 2
  HIGH_SAFEBOUND_LEVERAGE: 2.25
  HIGH_BOUND_LEVERAGE: 3

coldStorage:
  minOnChainHotWalletBalance: 1000000 # 0.1
  minRebalanceSize: 10000000 # 0.1
  maxHotWalletBalance: 200000000 # 2
  
  # pattern used to load cold storage wallet balances
  # string.include() is being used as a filter
  walletPattern: "specter"

  # select which bitcoind wallet is used for automatic rebalancing
  onChainWallet: "specter/coldstorage"

  # number of blocks in which a rebalance transaction is expected to be confirmed
  targetConfirmations: 6

lndScbBackupBucketName: "lnd-static-channel-backups"

test_accounts:
- ref: A
  phone: "+16505554321"
  code: "321321"
- ref: B
  phone: "+16505554322"
  code: "321432"
  phoneMetadataCarrierType: "mobile" # TODO: verify mobile is a valid value
- ref: C
  phone: "+16505554323"
  code: "321321"
  title: business
- ref: D
  phone: "+16505554324"
  code: "321321"
- ref: E
  phone: "+16505554332"
  code: "321321"
- ref: F
  phone: "+16505554333"
  code: "321321"
- ref: "G"
  phone: "+16505554335"
  code: "321321"
  username: "user15"

rateLimits:
  requestPhoneCodePerPhone:
    points: 4
    duration: 3600 # 60 * 60 s
    blockDuration: 10800 # 60 * 60 * 3 s
  requestPhoneCodePerPhoneMinInterval:
    points: 1
    duration: 15
    blockDuration: 15
  requestPhoneCodePerIp:
    points: 4
    duration: 3600 # 60 * 60 * 3 s
    blockDuration: 86400 # 60 * 60 s
  failedLoginAttemptPerPhone:
    points: 8
    duration: 1200 # 60 * 20 s
    blockDuration: 3600 # 60 * 60 s
  failedLoginAttemptPerIp:
    points: 20
    duration: 21600 # 60 * 60 * 6 s
    blockDuration: 86400 # 60 * 60 * 24 s
  invoiceCreateAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  invoiceCreateForRecipientAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  onChainAddressCreateAttempt:
    points: 20
    duration: 3600
    blockDuration: 14400 # 60 * 60 * 4 s  # 4 hours

accountLimits:
  withdrawal:
    level:
      1: 100000 # cents
      2: 5000000 # cents
  intraLedger:
    level:
      1: 2000 # cents
      2: 50000 # cents

spamLimits:
  memoSharingSatsThreshold: 1000

twoFALimits:
  threshold: 10000 # cents

ipRecording:
  enabled: true
  proxyChecking:
    enabled: true

# blacklistedIPTypes: ['VPN', 'Compromised Server']

# blacklistedIPs: ['1.2.3.4', '5.6.7.8']

fees:
  withdraw: 2000 # 2000 sats flat per tx
  deposit: 0.003 # 0.3 percent

withdrawFeeRange:
  min: 0 # sats
  max: 50000 # sats

lnds:
  - name: LND1
    type: ["offchain", "onchain"]
    priority: 2 # lower number means higher priority
  - name: LND2
    type: ["offchain"]
    priority: 3

onChainWallet:
  dustThreshold: 5000
  minConfirmations: 2
  scanDepth: 360
  scanDepthOutgoing: 2
  scanDepthChannelUpdate: 8

# TODO
# carrierRegexFilter: ""

apollo:
  playground: true
  playgroundUrl: "https://api.staging.galoy.io/graphql"

userActivenessMonthlyVolumeThreshold: 100 # cents
