name: "Galoy Banking"

lightningAddressDomain: "pay.domain.com"
lightningAddressDomainAliases: ["pay1.domain.com", "pay2.domain.com"]

locale: "en"

displayCurrency:
  code: "USD"
  symbol: "$"

# username of the account that will be used to fund rewards
funder: "FunderWallet"

dealer:
  usd:
    hedgingEnabled: false

ratioPrecision: 1_000_000

buildVersion:
  android:
    minBuildNumber: 182
    lastBuildNumber: 294
  ios:
    minBuildNumber: 182
    lastBuildNumber: 269

rewards:
  denyPhoneCountries: []
  allowPhoneCountries: [SV]
  denyIPCountries: []
  allowIPCountries: []
  denyASNs: []
  allowASNs: []

coldStorage:
  minOnChainHotWalletBalance: 1000000 # 0.1
  minRebalanceSize: 10000000 # 0.1
  maxHotWalletBalance: 200000000 # 2

  # pattern used to load cold storage wallet balances
  # string.include() is being used as a filter
  walletPattern: "specter"

  # select which bitcoind wallet is used for automatic rebalancing
  onChainWallet: "specter/coldstorage"

  # number of blocks in which a rebalance transaction is expected to be confirmed
  targetConfirmations: 6

lndScbBackupBucketName: "lnd-static-channel-backups"

test_accounts:
- ref: A
  phone: "+16505554321"
  code: "321321"
  needUsdWallet: true
- ref: B
  phone: "+16505554322"
  code: "321432"
  phoneMetadataCarrierType: "mobile" # TODO: verify mobile is a valid value
  needUsdWallet: true
- ref: C
  phone: "+16505554323"
  code: "321321"
  title: business
- ref: D
  phone: "+16505554324"
  code: "321321"
  needUsdWallet: true
- ref: E
  phone: "+16505554332"
  code: "321321"
- ref: F
  phone: "+16505554333"
  code: "321321"
  needUsdWallet: true
- ref: "G"
  phone: "+16505554335"
  code: "321321"
  username: "user15"
- ref: "H"
  phone: "+19876543210"
  code: "321321"
  username: "tester"
- ref: "I"
  phone: "+19876543336"
  code: "321321"
  role: "editor"
  username: "editor"

rateLimits:
  requestPhoneCodePerPhone:
    points: 4
    duration: 3600 # 60 * 60 s
    blockDuration: 10800 # 60 * 60 * 3 s
  requestPhoneCodePerPhoneMinInterval:
    points: 1
    duration: 15
    blockDuration: 15
  requestPhoneCodePerIp:
    points: 8
    duration: 3600 # 60 * 60 s
    blockDuration: 86400 # 60 * 60 * 24 s
  failedLoginAttemptPerPhone:
    points: 8
    duration: 1200 # 60 * 20 s
    blockDuration: 3600 # 60 * 60 s
  failedLoginAttemptPerEmailAddress:
    points: 8
    duration: 1200 # 60 * 20 s
    blockDuration: 3600 # 60 * 60 s
  failedLoginAttemptPerIp:
    points: 20
    duration: 21600 # 60 * 60 * 6 s
    blockDuration: 86400 # 60 * 60 * 24 s
  invoiceCreateAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  invoiceCreateForRecipientAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  onChainAddressCreateAttempt:
    points: 20
    duration: 3600
    blockDuration: 14400 # 60 * 60 * 4 s  # 4 hours

accounts:
  initialStatus: active

accountLimits:
  withdrawal:
    level:
      1: 100000 # cents
      2: 5000000 # cents
  intraLedger:
    level:
      1: 200000 # cents
      2: 5000000 # cents

spamLimits:
  memoSharingSatsThreshold: 1000

twoFALimits:
  threshold: 10000 # cents

ipRecording:
  enabled: true
  proxyChecking:
    enabled: true

fees:
  withdraw:
    method: "flat" # flat || proportionalOnImbalance
    defaultMin: 2000 # 2000 sats flat per tx
    ratio: 0.005 # only used with "proportional-on-imbalance"
    threshold: 1000000 # only used with "proportional-on-imbalance"
    daysLookback: 30 # only used with "proportional-on-imbalance"
  deposit: 0.003 # 0.3 percent

lnds:
  - name: LND1
    type: ["offchain", "onchain"]
    priority: 2 # lower number means higher priority
  - name: LND2
    type: ["offchain"]
    priority: 3

onChainWallet:
  dustThreshold: 5000
  minConfirmations: 2
  scanDepth: 360
  scanDepthOutgoing: 2
  scanDepthChannelUpdate: 8

apollo:
  playground: true
  playgroundUrl: "https://api.staging.galoy.io/graphql"

userActivenessMonthlyVolumeThreshold: 100 # cents

cronConfig:
  rebalanceEnabled: true

kratosConfig:
  serverURL: "http://localhost:4433"
  corsAllowedOrigins: ["http://localhost:3000"]

captcha:
  mandatory: false

skipFeeProbe:
  - "038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6" # Muun
