name: "Galoy Banking"

# username of the account that will be used to fund rewards
funder: "FunderWallet"

buildVersion:
  android:
    minBuildNumber: 182
    lastBuildNumber: 294
  ios:
    minBuildNumber: 182
    lastBuildNumber: 269

hedging:
  LOW_BOUND_RATIO_SHORTING: 0.95
  LOW_SAFEBOUND_RATIO_SHORTING: 0.98
# average: 0.99
  HIGH_SAFEBOUND_RATIO_SHORTING: 1
  HIGH_BOUND_RATIO_SHORTING: 1.03

# take a target leverage and safe parameter and calculate those bounding values dynamically.
  LOW_BOUND_LEVERAGE: 1.2
  LOW_SAFEBOUND_LEVERAGE: 1.8
#  // average: 2
  HIGH_SAFEBOUND_LEVERAGE: 2.25
  HIGH_BOUND_LEVERAGE: 3

rebalancing:
  minOnChainHotWalletBalance: 1000000 # 0.1
  minRebalanceSize: 10000000 # 0.1
  maxHotWalletBalance: 200000000 # 2

  # select which bitcoind wallet is used for rebalancing
  # string.include() is being used as a filter
  #
  # specter wallet always
  onchainWallet: "specter"

test_accounts:
- phone: "+16505554321" # user0
  code: 321321
- phone: "+16505554322" # user1
  code: 321432
  phoneMetadataCarrierType: "mobile" # TODO: verify mobile is a valid value
- phone: "+16505554323" # user2
  code: 321321
  title: business
- phone: "+16505554324" # user3
  code: 321321
- phone: "+16505554325" # user4/ funder
  code: 321321
  username: "FunderWallet"
  role: funder
- phone: "+16505554326"
  code: 321321
  currencies: [{id: "USD", ratio: 1}]
- phone: "+16505554327"
  code: 321321
  role: "dealer"
- phone: "+16505554328"
  code: 321321
- phone: "+16505554329" # postman
  code: 321321
- phone: "+16505554330"
  code: 321321
  currencies: [{id: "USD", ratio: .5}, {id: "BTC", ratio: .5},]
- phone: "+16505554331" # login fail attempt
  code: 321321
  currency: "BTC"
- phone: "+16505554332" # user11
  code: 321321
- phone: "+16505554333" # user12
  code: 321321
- phone: "+12223334444" # user13
  code: "424242"
  role: "editor"
- phone: "+16505554334" # user14
  code: 321321
  role: "bankowner"
- phone: "+16505554335" # user15
  code: 321321
  username: "user15"

limits:
  requestPhoneCodePerPhone:
    points: 4
    duration: 3600 # 60 * 60 s
    blockDuration: 10800 # 60 * 60 * 3 s
  requestPhoneCodePerPhoneMinInterval:
    points: 1
    duration: 15
    blockDuration: 15
  requestPhoneCodePerIp:
    points: 4
    duration: 3600 # 60 * 60 * 3 s
    blockDuration: 86400 # 60 * 60 s
  failedLoginAttemptPerPhone:
    points: 8
    duration: 1200 # 60 * 20 s
    blockDuration: 3600 # 60 * 60 s
  failedLoginAttemptPerIp:
    points: 20
    duration: 21600 # 60 * 60 * 6 s
    blockDuration: 86400 # 60 * 60 * 24 s
  invoiceCreateAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  invoiceCreateForRecipientAttempt:
    points: 20
    duration: 120
    blockDuration: 300
  onChainAddressCreateAttempt:
    points: 20
    duration: 3600
    blockDuration: 14400 # 60 * 60 * 4 s  # 4 hours
  memoSharingSatsThreshold: 1000
  withdrawal:
    level:
      1: 2000000
      2: 100000000
  onUs:
    level:
      1: 5000000
      2: 100000000

ipRecording:
  enabled: true
  proxyChecking:
    enabled: true

# blacklistedIPTypes: ['VPN', 'Compromised Server']

# blacklistedIPs: ['1.2.3.4', '5.6.7.8']

fees:
  withdraw: 2000 # 2000 sats flat per tx
  deposit: 0.003 # 0.3 percent

lnds:
  - name: LND1
    type: ["offchain", "onchain"]
    priority: 2 # lower number means higher priority
  - name: LND2
    type: ["offchain"]
    priority: 3

onChainWallet:
  dustThreshold: 5000
  minConfirmations: 2
  scanDepth: 360
  scanDepthOutgoing: 2
  scanDepthChannelUpdate: 8

# TODO
# carrierRegexFilter: ""

apollo:
  playground: true
  playgroundUrl: "https://api.staging.galoy.io/graphql"

twoFA:
  threshold: 300000 # sats

userActivenessMonthlyVolumeThreshold: 1000 # sats
