
name: "Galoy Banking"

# username of the account that will be used to fund rewards
funder: "FunderWallet"

hedging:
  LOW_BOUND_RATIO_SHORTING: 0.95
  LOW_SAFEBOUND_RATIO_SHORTING: 0.98
# average: 0.99
  HIGH_SAFEBOUND_RATIO_SHORTING: 1
  HIGH_BOUND_RATIO_SHORTING: 1.03

# take a target leverage and safe parameter and calculate those bounding values dynamically.
  LOW_BOUND_LEVERAGE: 1.2
  LOW_SAFEBOUND_LEVERAGE: 1.8
#  // average: 2
  HIGH_SAFEBOUND_LEVERAGE: 2.25
  HIGH_BOUND_LEVERAGE: 3

rebalancing:
  lndHoldingBase: 50000000 # 0.5
  ratioTargetDeposit: 1
  ratioTargetWithdraw: 1
  minOnchain: 10000000 # 0.1

  # select which bitcoind wallet is used for rebalancing
  # string.include() is being used as a filter
  # 
  # specter wallet always 
  onchainWallet: "specter"

test_accounts: 
- phone: "+16505554321" # user0
  code: 321321
- phone: "+16505554322" # user1
  code: 321321
- phone: "+16505554323" # user2
  code: 321321
  title: business
- phone: "+16505554324" # user3
  code: 321321
- phone: "+16505554325" # user4/ funder
  code: 321321
  username: "FunderWallet"
- phone: "+16505554326"
  code: 321321
  currencies: [{id: "USD", ratio: 1}]
- phone: "+16505554327"
  code: 321321
  role: "dealer"
- phone: "+16505554328"
  code: 321321
- phone: "+16505554329" # postman
  code: 321321 
- phone: "+16505554330"
  code: 321321
  currencies: [{id: "USD", ratio: .5}, {id: "BTC", ratio: .5},]
- phone: "+16505554331" # login fail attempt
  code: 321321
  currency: "BTC"

limits:
  requestPhoneCode:
    points: 4
    duration: 10800 # 60 * 60 * 3 s
    blockDuration: 3600 # 60 * 60 s
  loginAttempt:
    points: 8
    duration: 1200 # 60 * 20 s
    blockDuration: 3600 # 60 * 60 s 
  failedAttemptPerIp:
    points: 30
    duration: 21600 # 60 * 60 * 6 s 
    blockDuration: 86400 # 60 * 60 * 24 s
  oldEnoughForWithdrawal: 172800000 # 1000 * 60 * 60 * 24 * 2, in ms # 2 days
  withdrawal:
    level:
      1: 2000000
      2: 100000000
  onUs:
    level:
      1: 5000000
      2: 100000000
  pendingPayments:
    semaphoreLockTimeout: 1800000 # 30 mins 
    level:
      1: 3
      2: 7

proxyChecking:
  enabled: true

fees:
  withdraw: 2000 # 2000 sats flat per tx
  deposit: 0.003 # 0.3 percent

# TODO
# carrierRegexFilter: ""

