FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

COPY ./*.json ./yarn.lock ./

RUN yarn install --frozen-lockfile

COPY ./src ./src
COPY ./test ./test

RUN yarn build

COPY ./scripts ./scripts

FROM node:20-alpine
COPY --from=BUILD_IMAGE /app/lib /app/lib
COPY --from=BUILD_IMAGE /app/src/config/locales /app/lib/config/locales
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules
COPY --from=BUILD_IMAGE /app/scripts /app/scripts

WORKDIR /app
COPY ./*.js ./package.json ./tsconfig.json ./yarn.lock ./
RUN touch .env

### debug only
COPY --from=BUILD_IMAGE /app/src /app/src
COPY --from=BUILD_IMAGE /app/test /app/test
COPY ./junit.xml ./
###

USER 1000

ARG COMMITHASH
ENV COMMITHASH ${COMMITHASH}

ENTRYPOINT ["scripts/mongodb-migrate.sh"]
