FROM node:14-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

COPY ./package.json ./tsconfig.json ./yarn.lock ./

RUN yarn install --frozen-lockfile

COPY ./src ./src
RUN yarn build

FROM gcr.io/distroless/nodejs:14-debug
COPY --from=BUILD_IMAGE /app/lib /app/lib
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules

WORKDIR /app
COPY ./*.js ./default.yaml ./package.json ./tsconfig.json ./yarn.lock ./.env ./
RUN touch junit.xml

USER 1000

ENTRYPOINT ["/busybox/sleep", "1d"]

# /nodejs/bin/node lib/entrypoint/graphql.js