federation_version: =2.3.2
subgraphs:
  public:
    routing_url: http://bats-tests:4012/graphql
    schema:
      file: ../../src/graphql/main/schema.graphql
  circles:
    routing_url: http://localhost:4000
    schema:
      file: ../../../blink-circles/src/graphql/schema.graphql # relative path to https://github.com/GaloyMoney/blink-circles
