load(
  "@prelude//toolchains:python.bzl",
  "system_python_bootstrap_toolchain",
  "system_python_toolchain"
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

load("@toolchains//simple-pnpm:toolchain.bzl", "simple_pnpm_toolchain")

simple_pnpm_toolchain(
  name = "simple_pnpm",
  visibility = ["PUBLIC"],
)

load("@toolchains//workspace-pnpm:toolchain.bzl", "workspace_pnpm_toolchain")

workspace_pnpm_toolchain(
  name = "workspace_pnpm",
  visibility = ["PUBLIC"],
)
