docker_compose("./docker-compose.deps.yml", ".env","galoy-dev")

groups = {
    "bitcoin": [
        "lnd1",
        "bria",
        "postgres-bria",
        "fulcrum",
        "bitcoind-signer",
        "bitcoind",
    ],
    "tracing": [
      "otel-agent",
    ],
}
for service in groups["bitcoin"]:
    dc_resource(service, labels = ["bitcoin"])

local_resource(
  name='init-onchain',
  labels = ['bitcoin'],
  cmd='bin/init-onchain.sh',
  resource_deps = [
    "bitcoind",
    "bria",
  ]
)
