config.define_string_list("test")
config.define_string_list("to-run", args = True)
cfg = config.parse()

is_ci=("ci" in sys.argv)

def _buck2_dep_inputs(target):
    cmd = [
        "buck2",
        "uquery",
        "\"inputs(deps('{}'))\"".format(target),
    ]
    file_paths = str(local(" ".join(cmd))).splitlines()

    return file_paths

dashboard_target = "//apps/dashboard:dev"
if is_ci:
  dashboard_target = '//apps/dashboard:dashboard'
local_resource(
    "dashboard",
    labels = ["apps"],
    cmd = "buck2 build {}".format(dashboard_target),
    serve_cmd = ". .envs/dashboard.env && buck2 run {}".format(dashboard_target),
    serve_env = {
      "NEXTAUTH_URL": "http://localhost:3001",
      "NEXTAUTH_SECRET": "secret",
      "PORT": "3001",
    },
    deps = _buck2_dep_inputs(dashboard_target),
    resource_deps = [
        "hydra-dashboard",
    ],
    links = [
        link("http://localhost:3001", "dashboard"),
    ],
)

local_resource(
  name='hydra-dashboard',
  labels = ['apps'],
  cmd=[
    'buck2',
    'run',
    '//dev:setup-hydra-client',
    '--',
    'dashboard',
    'http://localhost:3001/api/auth/callback/blink'
  ],
  resource_deps = [
    "hydra",
  ]
)

consent_test_target = "//apps/consent:test-integration"
local_resource(
  "consent-test",
  labels = ["test"],
  auto_init = is_ci and "consent" in cfg.get("test", []),
  cmd = "buck2 test {}".format(consent_test_target),
  resource_deps = [
    "consent",
    "init-test-user",
    "hydra-consent"
  ],
)

local_resource(
  name='init-test-user',
  labels = ['test'],
  cmd='buck2 run //dev:init-user',
  resource_deps = [
    "oathkeeper",
    "kratos",
    "api",
  ]
)

consent_target = "//apps/consent:dev"
if is_ci:
  consent_target = '//apps/consent:consent'
local_resource(
    "consent",
    labels = ["auth"],
    cmd = "buck2 build {}".format(consent_target),
    serve_cmd = "buck2 run {}".format(consent_target),
    deps = _buck2_dep_inputs(consent_target),
    resource_deps = [
        "apollo-router",
        "hydra",
        "api",
    ],
    links = [
        link("http://localhost:3000", "consent"),
    ],
)

local_resource(
  name='hydra-consent',
  labels = ['apps'],
  cmd=[
    'buck2',
    'run',
    '//dev:setup-hydra-client',
    '--',
    'consent',
    'http://localhost:3000'
  ],
  resource_deps = [
    "hydra",
  ]
)

api_target = "//core/api:api"
local_resource(
    "api",
    labels = ["core"],
    cmd = "buck2 build {}".format(api_target),
    serve_cmd = "buck2 run {}".format(api_target),
    serve_env = {
        "HELMREVISION": "dev",
        "NETWORK": "regtest",
        "OATHKEEPER_DECISION_ENDPOINT": "http://localhost:4456",
        "TWILIO_ACCOUNT_SID": "AC_twilio_id",
        "TWILIO_AUTH_TOKEN": "AC_twilio_auth_token",
        "TWILIO_VERIFY_SERVICE_ID": "VA_twilio_service",
        "KRATOS_PG_CON": "postgres://dbuser:secret@localhost:5433/default?sslmode=disable",
        "KRATOS_PUBLIC_API": "http://localhost:4433",
        "KRATOS_ADMIN_API": "http://localhost:4434",
        "KRATOS_MASTER_USER_PASSWORD": "passwordHardtoFindWithNumber123",
        "KRATOS_CALLBACK_API_KEY": "The-Value-of-My-Key",
        "BRIA_HOST": "localhost",
        "BRIA_API_KEY": "bria_dev_000000000000000000000",
        "MONGODB_CON": "mongodb://localhost:27017/galoy",
        "REDIS_MASTER_NAME": "mymaster",
        "REDIS_PASSWORD": "",
        "REDIS_0_DNS": "localhost",
        "REDIS_0_PORT": "6379",
        "REDIS_TYPE": "standalone",
        "UNSECURE_IP_FROM_REQUEST_OBJECT": "true",
        "UNSECURE_DEFAULT_LOGIN_CODE": "000000",
        "GEETEST_ID": "geetest_id",
        "GEETEST_KEY": "geetest_key"
    },
    allow_parallel = True,
    readiness_probe = probe(
        period_secs  = 5,
        http_get = http_get_action(
            path = "healthz",
            port = 4012,
        ),
    ),
    deps = _buck2_dep_inputs(api_target),
    resource_deps = [
        "init-onchain",
        "lnd1",
        "redis",
        "mongodb",
        "oathkeeper",
    ]
)

local_resource(
  name='init-onchain',
  labels = ['bitcoin'],
  cmd='buck2 run //dev:init-onchain',
  resource_deps = [
    "bitcoind",
    "bria",
  ]
)

def _buck2_dep_inputs(target):
    cmd = [
        "buck2",
        "uquery",
        "\"inputs(deps('{}'))\"".format(target),
    ]
    file_paths = str(local(" ".join(cmd))).splitlines()

    return file_paths

api_keys_target = "//core/api-keys:api-keys"
local_resource(
    "api_keys",
    labels = ["core"],
    cmd = "buck2 build {}".format(api_keys_target),
    serve_cmd = "buck2 run {} -- run".format(api_keys_target),
    deps = _buck2_dep_inputs(api_keys_target),
)

docker_groups = {
    "auth": [
        "oathkeeper",
        "hydra",
        "hydra-migrate",
        "hydra-pg",
        "kratos",
        "kratos-pg",
    ],
    "core": [
        "apollo-router",
        "mongodb",
        "redis",
    ],
    "bitcoin": [
        "lnd1",
        "bria",
        "bitcoind",
    ],
    "tracing": [
      "otel-agent",
    ],
}

to_run = cfg.get("to-run", [])
if to_run != []:
    enabled_resources = []
    for svc in to_run:
      enabled_resources.append(svc)
    config.set_enabled_resources(enabled_resources)

docker_compose("./docker-compose.deps.yml", project_name = "galoy-dev")

for service in docker_groups["bitcoin"]:
    dc_resource(service, labels = ["bitcoin"])
for service in docker_groups["tracing"]:
    dc_resource(service, labels = ["tracing"])
for service in docker_groups["core"]:
    dc_resource(service, labels = ["core"])
for service in docker_groups["auth"]:
    dc_resource(service, labels = ["auth"])
