import { testData } from "../../support/test-data"

describe("Callback Test", () => {
  beforeEach(() => {
    cy.viewport(1920, 1080)
    cy.setCookie("next-auth.session-token", testData.NEXT_AUTH_SESSION_TOKEN, {
      secure: true,
    })
    cy.visit("/")
    cy.get("[data-testid=sidebar-api-keys-link]")
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
  })

  it("Api Key creation Test", () => {
    cy.get('[data-testid="create-api-add-btn"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
    cy.get('[data-testid="create-api-name-input"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .type("New API Key")
    cy.get('[data-testid="create-api-expire-select"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
    cy.get('[data-testid="create-api-expire-30-days-select"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
    cy.get('[data-testid="create-api-create-btn"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
    cy.get('[data-testid="create-api-close-btn"]')
      .should("exist")
      .and("be.visible")
      .and("not.be.disabled")
      .click()
  })
})
