load(
  "@toolchains//workspace-pnpm:macros.bzl",
  "runnable_tsc_build_bin",
)

alias(
    name = "runnable_build",
    actual = "//core/api:runnable_build",
)

runnable_tsc_build_bin(
  name = "api-trigger",
  preload_file = "services/tracing.js",
  run_file = "servers/trigger.js",
)
