load(
  "@toolchains//workspace-pnpm:macros.bzl",
  "dev_pnpm_task_binary",
  "prod_tsc_build_bin",
)

alias(
    name = "prod_build",
    actual = "//core/api:prod_build",
)

prod_tsc_build_bin(
  name = "api-trigger",
  preload_file = "services/tracing.js",
  run_file = "servers/trigger.js",
)

dev_pnpm_task_binary(
  name = "dev",
  command = "dev:api-trigger",
  package_dir = "core/api",
  srcs = ["//core/api:src"],
)
