FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

RUN npm install -g pnpm

COPY tmp/workspace/* ./

RUN mkdir -p core/api
WORKDIR /app/core/api

COPY ./*.json ./

RUN pnpm install --frozen-lockfile

COPY ./src ./src
COPY ./test ./test

RUN pnpm run build

COPY ./scripts ./scripts

FROM node:20-alpine
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules
COPY --from=BUILD_IMAGE /app/core/api/dist /app/core/api/dist
COPY --from=BUILD_IMAGE /app/core/api/src/config/locales /app/core/api/dist/config/locales
COPY --from=BUILD_IMAGE /app/core/api/node_modules /app/core/api/node_modules
COPY --from=BUILD_IMAGE /app/core/api/scripts /app/core/api/scripts

WORKDIR /app/core/api
COPY ./*.js ./package.json ./tsconfig.json ./
RUN touch .env

### debug only
COPY --from=BUILD_IMAGE /app/core/api/src /app/core/api/src
COPY --from=BUILD_IMAGE /app/core/api/test /app/core/api/test
COPY ./junit.xml ./
###

USER 1000

ARG COMMITHASH
ENV COMMITHASH ${COMMITHASH}

ENTRYPOINT ["scripts/mongodb-migrate.sh"]
