FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

RUN npm install -g pnpm

RUN mkdir -p core/api/
COPY ./core/api/*.json ./core/api/
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

WORKDIR /app/core/api

RUN pnpm install --frozen-lockfile

COPY ./core/api/src ./src
COPY ./core/api/test ./test

RUN pnpm run build

FROM node:20-alpine
COPY --from=BUILD_IMAGE /app/core/api/dist /app/core/api/dist
COPY --from=BUILD_IMAGE /app/core/api/src/config/locales /app/core/api/dist/config/locales
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules
COPY --from=BUILD_IMAGE /app/core/api/node_modules /app/core/api/node_modules

WORKDIR /app/core/api
COPY ./core/api/*.js ./core/api/package.json ./core/api/tsconfig.json ./
RUN touch .env

### debug only
COPY --from=BUILD_IMAGE /app/core/api/src /app/core/api/src
COPY --from=BUILD_IMAGE /app/core/api/test /app/core/api/test
COPY ./core/api/junit.xml ./
###

USER 1000

ARG COMMITHASH
ENV COMMITHASH ${COMMITHASH}

CMD ["pnpm", "run", "mongodb-migrate"]
