FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

RUN npm install -g pnpm

RUN mkdir -p core/api/
COPY ./core/api/*.json ./core/api/
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

WORKDIR /app/core/api

RUN pnpm install --frozen-lockfile

COPY ./core/api/src ./src

RUN pnpm run build

RUN pnpm install --frozen-lockfile --prod

RUN touch .env

FROM gcr.io/distroless/nodejs20-debian11
COPY --from=BUILD_IMAGE /app/core/api/dist /app/core/api/dist
COPY --from=BUILD_IMAGE /app/core/api/src/config/locales /app/core/api/dist/config/locales
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules
COPY --from=BUILD_IMAGE /app/core/api/node_modules /app/core/api/node_modules
COPY --from=BUILD_IMAGE /app/core/api/.env /app/core/api/.env

WORKDIR /app/core/api
COPY ./core/api/*.js ./core/api/package.json ./core/api/tsconfig.json ./

USER 1000

ARG COMMITHASH
ENV COMMITHASH ${COMMITHASH}

CMD ["dist/servers/ws-server.js"]
