FROM node:20-alpine AS BUILD_IMAGE

WORKDIR /app

RUN apk update && apk add git

RUN npm install -g pnpm

COPY ./*.json ./

RUN pnpm install

COPY ./src ./src
COPY ./test ./test

RUN pnpm run build

COPY ./scripts ./scripts

FROM node:20-alpine
COPY --from=BUILD_IMAGE /app/dist /app/dist
COPY --from=BUILD_IMAGE /app/src/config/locales /app/dist/config/locales
COPY --from=BUILD_IMAGE /app/node_modules /app/node_modules
COPY --from=BUILD_IMAGE /app/scripts /app/scripts

WORKDIR /app
COPY ./*.js ./package.json ./tsconfig.json ./
RUN touch .env

### debug only
COPY --from=BUILD_IMAGE /app/src /app/src
COPY --from=BUILD_IMAGE /app/test /app/test
COPY ./junit.xml ./
###

USER 1000

ARG COMMITHASH
ENV COMMITHASH ${COMMITHASH}

ENTRYPOINT ["scripts/mongodb-migrate.sh"]
