spectaql:
  logoFile: ./public/logo.png
introspection:
  schemaFile: ./src/graphql/public/schema.graphql
info:
  title: GraphQL API Reference
  description: Welcome to the Galoy API reference!
  contact:
    name: Galoy developer community
    url: https://chat.galoy.io/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-introItems:
  - title: Galoy API Tutorial
    description: |
      ## Overview
      Find detailed documentation of the hosted production API at [dev.blink.sv](https://dev.blink.sv)
      * The production API endpoint is: `https://api.blink.sv/graphql`

      ## Authentication
      * To get an API key register with a phone number or log in with your existing Blink account on [dashboard.blink.sv](https://dashboard.blink.sv).
      Use the same credentials as with the Blink wallet app.
      * for your custom requests set the API key in the header as:
          ```
          "X-API-KEY" "blink_..."
          ```

      ## Extra Resources

      If you use Postman, we have a collection you can import to test the API. Find it at [dev.blink.sv/api/postman](https://dev.blink.sv/api/postman)
servers:
- url: https://api.blink.sv/graphql
  description: Blink API
  production: true
