export_file(
    name = "package.json",
    visibility = ["PUBLIC"],
)

filegroup(
    name = "src",
    srcs = [
        ".eslintrc.base.js",
        ".prettier.config.js",
    ],
    visibility = ["PUBLIC"],
)
