export const QuizzesSectionsConfig = [
  {
    section: "bitcoinWhatIsIt",
    quiz: [
      "whatIsBitcoin",
      "sat",
      "whereBitcoinExist",
      "whoControlsBitcoin",
      "copyBitcoin",
    ],
  },
  {
    section: "WhatIsMoney",
    quiz: [
      "moneySocialAgreement",
      "coincidenceOfWants",
      "moneyEvolution",
      "whyStonesShellGold",
      "moneyIsImportant",
      "moneyImportantGovernement",
    ],
  },
  {
    section: "HowDoesMoneyWork",
    quiz: [
      "WhatIsFiat",
      "whyCareAboutFiatMoney",
      "GovernementCanPrintMoney",
      "FiatLosesValueOverTime",
      "OtherIssues",
    ],
  },
  {
    section: "BitcoinWhySpecial",
    quiz: [
      "LimitedSupply",
      "Decentralized",
      "NoCounterfeitMoney",
      "HighlyDivisible",
      "securePartOne",
      "securePartTwo",
    ],
  },
  {
    section: "TheOriginsOfMoney",
    quiz: [
      "originsOfMoney",
      "primitiveMoney",
      "anticipatingDemand",
      "nashEquilibrium",
      "singleStoreOfValue",
    ],
  },
  {
    section: "AttributesOfAGoodStoreOfValue",
    quiz: [
      "whatIsGoodSOV",
      "durability",
      "portability",
      "fungibility",
      "verifiability",
      "divisibility",
      "scarce",
      "establishedHistory",
      "censorshipResistance",
    ],
  },
  {
    section: "TheEvolutionOfMoneyI",
    quiz: [
      "evolutionMoney",
      "collectible",
      "storeOfValue",
      "mediumOfExchange",
      "unitOfAccount",
      "partlyMonetized",
      "monetizationStage",
    ],
  },
  {
    section: "TheEvolutionOfMoneyII",
    quiz: [
      "notFromGovernment",
      "primaryFunction",
      "monetaryMetals",
      "stockToFlow",
      "hardMoney",
    ],
  },
  {
    section: "TheEvolutionOfMoneyIII",
    quiz: [
      "convergingOnGold",
      "originsOfPaperMoney",
      "fractionalReserve",
      "bankRun",
      "modernCentralBanking",
      "goldBacked",
      "brettonWoods",
      "globalReserve",
    ],
  },
  {
    section: "TheEvolutionOfMoneyIV",
    quiz: [
      "nixonShock",
      "fiatEra",
      "digitalFiat",
      "plasticCredit",
      "doubleSpendProblem",
      "satoshisBreakthrough",
      "nativelyDigital",
      "CBDCs",
    ],
  },
  {
    section: "BitcoinWhyWasItCreated",
    quiz: [
      "rootProblem",
      "bitcoinCreator",
      "fiatRequiresTrust",
      "moneyPrinting",
      "genesisBlock",
      "cypherpunks",
    ],
  },
  {
    section: "BitcoinHowDoesItWork",
    quiz: [
      "peer2Peer",
      "blockchain",
      "privateKey",
      "publicKey",
      "mining",
      "proofOfWork",
      "difficultyAdjustment",
      "halving",
    ],
  },
  {
    section: "LightningWhatDoesItSolve",
    quiz: [
      "bitcoinDrawbacks",
      "blocksizeWars",
      "lightningNetwork",
      "instantPayments",
      "micropayments",
      "scalability",
      "paymentChannels",
      "routing",
    ],
  },
  {
    section: "BitcoinCriticismsFallaciesI",
    quiz: [
      "itsaBubble",
      "itstooVolatile",
      "itsnotBacked",
      "willbecomeObsolete",
      "toomuchEnergy",
      "strandedEnergy",
    ],
  },
  {
    section: "BitcoinCriticismsFallaciesII",
    quiz: [
      "internetDependent",
      "forcrimeOnly",
      "ponziScheme",
      "bitcoinisTooSlow",
      "supplyLimit",
      "governmentBan",
    ],
  },
  {
    section: "BitcoinCriticismsFallaciesIII",
    quiz: [
      "concentratedOwnership",
      "centralizedMining",
      "tooExpensive",
      "prohibitivelyHigh",
      "willBeHoarded",
      "canBeDuplicated",
    ],
  },
  {
    section: "BitcoinAndEconomicsI",
    quiz: [
      "scarcity",
      "monetaryPremium",
      "greshamsLaw",
      "thiersLaw",
      "cantillonEffect",
      "schellingPoint",
    ],
  },
  {
    section: "BitcoinAndEconomicsII",
    quiz: [
      "opportunityCost",
      "timePreference",
      "impossibleTrinity",
      "jevonsParadox",
      "powerLaws",
      "winnerTakeAll",
    ],
  },
  {
    section: "BitcoinAndEconomicsIII",
    quiz: ["unitBias", "veblenGood", "malinvestment", "asymmetricPayoff", "ansoffMatrix"],
  },
] as const
