#@data/values
---
version: "3"
services:
  apollo-router:
    ports:
      - "4004:4004"
    extra_hosts:
      - "bats-tests:host-gateway"
  otel-agent:
    ports:
      - "4318:4318" #! http receiver
  price:
    ports:
      - "50051:50051"
      - "9464:9464"
  price-history:
    ports:
      - "50052:50052"
  redis:
    ports:
      - "6379:6379"
  mongodb:
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
    ports:
      - "27017:27017"
  postgres-price-history:
    ports:
      - "5432:5432"
  bitcoind:
    ports:
      - "18443:18443"
  bitcoind-signer:
    ports:
      - "18543:18443"
  lnd1:
    ports:
      - "10009:10009"
  lnd2:
    ports:
      - "10010:10009"
  lnd-outside-1:
    ports:
      - "10012:10009"
  lnd-outside-2:
    ports:
      - "10013:10009"
  lnd-outside-3:
    ports:
      - "10014:10009"
  stablesats:
    ports:
      - "3325:3325"
  bria:
    ports:
      - "2743:2743"
      - "2742:2742"
  loopserver:
    ports:
      - "11009:11009"
  loopd1:
    ports:
      - "8081:8081"
      - "11010:11010"
  loopd2:
    ports:
      - "8082:8081"
      - "11011:11010"
  oathkeeper:
    extra_hosts:
      - "bats-tests:host-gateway"
    ports:
      - "4002:4455"
      - "4456:4456"
  kratos:
    extra_hosts:
      - "bats-tests:host-gateway"
    ports:
      - "4433:4433" #! public
      - "4434:4434" #! admin
  bats-tests:
    ports:
      - "4012:4012"
      - "4001:4001"
      - "4000:4000"
  e2e-tests:
    ports:
      - "4012:4012"
      - "4001:4001"
      - "4000:4000"
  mailslurper:
    ports:
      - "4436:4436"
      - "4437:4437"
  kratos-pg:
    ports:
      - "5433:5432"
  fulcrum:
    ports:
      - "50001:50001"
  svix:
    ports:
      - "8071:8071"
    extra_hosts:
      - "bats-tests:host-gateway"
