load("@toolchains//simple-pnpm:macros.bzl", "build_node_modules", "npm_bin")

export_file(
  name = "pnpm-lock.yaml"
)

build_node_modules(
  name = "node_modules",
)

npm_bin(
  name = "turbo_bin",
  bin_name = "turbo",
  visibility = ["PUBLIC"],
)
