load("@toolchains//simple-pnpm:macros.bzl", "build_node_modules", "npm_bin")

export_file(
  name = "pnpm-lock.yaml"
)

build_node_modules(
  name = "node_modules",
  visibility = ["PUBLIC"],
  pnpm_lock = ":pnpm-lock.yaml",
)

npm_bin(
  name = "turbo"
)
