load("@toolchains//rust:macros.bzl", "galoy_rust_lib")

galoy_rust_lib(
    name = "es-entity",
    deps = [
        "//third-party/rust:thiserror",
        "//third-party/rust:derive_builder",
        "//third-party/rust:serde_json",
        "//third-party/rust:serde",
        "//third-party/rust:sqlx",
        "//third-party/rust:uuid",
    ],
    srcs = glob(["src/**/*.rs"]),
    env = {
        "CARGO_PKG_NAME": "es-entity" ,
        "CARGO_PKG_VERSION": "0.1.0" ,
    },
)
