rust_library(
    name = "es-entity",
    edition = "2021",
    deps = [
        "//third-party/rust:thiserror",
        "//third-party/rust:derive_builder",
        "//third-party/rust:serde_json",
    ],
    srcs = glob(["src/**/*.rs"]),
    env = {
        "CARGO_PKG_NAME": "es-entity" ,
        "CARGO_PKG_VERSION": "0.1.0" ,
    },
    visibility = ["PUBLIC"],
)
