{{ if .Values.adminIngress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.adminIngress.name }}
  labels:
    app: {{ .Values.adminIngress.name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/limit-rpm: "60"
spec:
  tls:
  - hosts:
    - {{.Values.adminIngress.host}}
    secretName: {{.Values.adminIngress.tlsSecretName}}
  rules:
  - host: {{.Values.adminIngress.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: graphql-admin
          servicePort: 4001
{{ end }}
