// source: services/price/v1/price_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf")
var goog = jspb
var global = Function("return this")()

goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest",
  null,
  global,
)
goog.exportSymbol(
  "proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse",
  null,
  global,
)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.displayName =
    "proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.displayName =
    "proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.displayName =
    "proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.displayName =
    "proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.displayName =
    "proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.displayName =
    "proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.displayName =
    "proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse"
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(
  proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse,
  jspb.Message,
)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.displayName =
    "proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse"
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        amountInSatoshis: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest()
    return proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setAmountInSatoshis(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getAmountInSatoshis()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float amount_in_satoshis = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.prototype.getAmountInSatoshis =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyRequest.prototype.setAmountInSatoshis =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        amountInUsd: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest()
    return proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setAmountInUsd(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getAmountInUsd()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float amount_in_usd = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.prototype.getAmountInUsd =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellRequest.prototype.setAmountInUsd =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        amountInSatoshis: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
        timeInSeconds: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest()
    return proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setAmountInSatoshis(value)
          break
        case 2:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setTimeInSeconds(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getAmountInSatoshis()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
    f = message.getTimeInSeconds()
    if (f !== 0.0) {
      writer.writeFloat(2, f)
    }
  }

/**
 * optional float amount_in_satoshis = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.getAmountInSatoshis =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.setAmountInSatoshis =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

/**
 * optional float time_in_seconds = 2;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.getTimeInSeconds =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyRequest.prototype.setTimeInSeconds =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 2, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        amountInUsd: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
        timeInSeconds: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest()
    return proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setAmountInUsd(value)
          break
        case 2:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setTimeInSeconds(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getAmountInUsd()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
    f = message.getTimeInSeconds()
    if (f !== 0.0) {
      writer.writeFloat(2, f)
    }
  }

/**
 * optional float amount_in_usd = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.getAmountInUsd =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.setAmountInUsd =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

/**
 * optional float time_in_seconds = 2;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.getTimeInSeconds =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellRequest.prototype.setTimeInSeconds =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 2, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        priceInUsd: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse()
    return proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setPriceInUsd(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getPriceInUsd()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float price_in_usd = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.prototype.getPriceInUsd =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse} returns this
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdBuyResponse.prototype.setPriceInUsd =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        priceInSatoshis: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse()
    return proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setPriceInSatoshis(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getPriceInSatoshis()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float price_in_satoshis = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.prototype.getPriceInSatoshis =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse} returns this
 */
proto.services.price.v1.GetExchangeRateForImmediateUsdSellResponse.prototype.setPriceInSatoshis =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        priceInUsd: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse()
    return proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setPriceInUsd(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getPriceInUsd()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float price_in_usd = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.prototype.getPriceInUsd =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdBuyResponse.prototype.setPriceInUsd =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.prototype.toObject =
    function (opt_includeInstance) {
      return proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.toObject(
        opt_includeInstance,
        this,
      )
    }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        priceInSatoshis: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes)
    var msg = new proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse()
    return proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.deserializeBinaryFromReader(
      msg,
      reader,
    )
  }

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setPriceInSatoshis(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.serializeBinaryToWriter(
      this,
      writer,
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined
    f = message.getPriceInSatoshis()
    if (f !== 0.0) {
      writer.writeFloat(1, f)
    }
  }

/**
 * optional float price_in_satoshis = 1;
 * @return {number}
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.prototype.getPriceInSatoshis =
  function () {
    return /** @type {number} */ (
      jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
    )
  }

/**
 * @param {number} value
 * @return {!proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse} returns this
 */
proto.services.price.v1.GetExchangeRateForFutureUsdSellResponse.prototype.setPriceInSatoshis =
  function (value) {
    return jspb.Message.setProto3FloatField(this, 1, value)
  }

goog.object.extend(exports, proto.services.price.v1)
