buildscript = []

[[platform_fixup.'cfg(target_os = "windows")'.buildscript]]
[platform_fixup.'cfg(target_os = "windows")'.buildscript.prebuilt_cxx_library]
name = "windows.lib"
static_libs = ["lib/windows.lib"]