type QuizQuestionId =
  | "walletDownloaded"
  | "walletActivated"
  | "whatIsBitcoin"
  | "sat"
  | "whereBitcoinExist"
  | "whoControlsBitcoin"
  | "copyBitcoin"
  | "moneyImportantGovernement"
  | "moneyIsImportant"
  | "whyStonesShellGold"
  | "moneyEvolution"
  | "coincidenceOfWants"
  | "moneySocialAggrement"
  | "WhatIsFiat"
  | "whyCareAboutFiatMoney"
  | "GovernementCanPrintMoney"
  | "FiatLosesValueOverTime"
  | "OtherIssues"
  | "LimitedSupply"
  | "Decentralized"
  | "NoCounterfeitMoney"
  | "HighlyDivisible"
  | "securePartOne"
  | "securePartTwo"

type SkipFeeProbeConfig = { pubkey: Pubkey[]; chanId: ChanId[] }
