mutation UserUpdatePhone($input: UserUpdatePhoneInput!) {
  userUpdatePhone(input: $input) {
    errors {
      __typename
      message
      code
      path
    }
    accountDetails {
      id
    }
  }
}
