#@ load("@ytt:data", "data")

spectaql:
  logoFile: ./public/logo.png

introspection:
  schemaFile: ./src/graphql/main/schema.graphql

info:
  title: GraphQL API Reference
  description: Welcome to the Galoy API reference!
  contact:
    name: Galoy slack developer community
    url: https://join.slack.com/t/galoymoney-workspace/shared_invite/zt-rvnhsdb5-72AZCD_jzw6_Q05aCs0SgA
  license:
    name: MIT 
    url: https://opensource.org/licenses/MIT
  x-introItems:
  - title: Galoy API Tutorial
    description: #@ data.read("TUTORIAL.md")


servers:
  - url: https://api.staging.galoy.io/graphql
    description: Testnet
    production: false
