#@ load("@ytt:data", "data")

spectaql:
  logoFile: ./public/logo.png

introspection:
  schemaFile: ./src/graphql/main/schema.graphql

info:
  title: GraphQL API Reference
  description: Welcome to the Galoy API reference!
  contact:
    name: Galoy developer community
    url: https://chat.galoy.io/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-introItems:
    - title: Galoy API Tutorial
      description: #@ data.read("TUTORIAL.md")

servers:
  - url: https://api.staging.galoy.io/graphql
    description: Testnet
    production: false
