mutation accountUpdatePushNotificationSettings($input: AccountUpdatePushNotificationSettingsInput!) {
  accountUpdatePushNotificationSettings(input: $input) {
    errors {
      message
    }
    account {
      pushNotificationSettings {
        pushNotificationsEnabled
        disabledPushNotificationTypes
      }
    }
  }
}
