mutation onChainUsdPaymentSendAsBtcDenominated(
  $input: OnChainUsdPaymentSendAsBtcDenominatedInput!
) {
  onChainUsdPaymentSendAsBtcDenominated(input: $input) {
    errors {
      message
    }
    status
  }
}
