mutation userTotpRegistrationInitiate($input: UserTotpRegistrationInitiateInput!) {
  userTotpRegistrationInitiate(input: $input) {
    errors {
      message
    }
    totpRegistrationId
    totpSecret
  }
}
