subscription realtimePrice(
  $currency: DisplayCurrency!
) {
  realtimePrice(
    input: {
      currency: $currency
    }
  ) {
    errors {
      message
    }
    realtimePrice {
      id
      timestamp
      denominatorCurrency
      btcSatPrice {
        base
        offset
        minorUnitToMajorUnitOffset
        currencyUnit
      }
      usdCentPrice {
        base
        offset
        minorUnitToMajorUnitOffset
        currencyUnit
      }
    }
  }
}
