subscription satPrice(
  $currency: DisplayCurrency!
) {
  satPrice(
    input: {
      currency: $currency
    }
  ) {
    errors {
      message
    }
    price {
      base
      offset
      currencyUnit
      formattedAmount
    }
  }
}
