#@ load("@ytt:data", "data")

spectaql:
  logoFile: ./public/logo.png

introspection:
  schemaFile: ./src/graphql/public/schema.graphql

info:
  title: GraphQL API Reference
  description: Welcome to the Blink API reference!
  contact:
    name: Blink developer community
    url: https://chat.blink.sv/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-introItems:
    - title: Blink API Tutorial
      description: #@ data.read("TUTORIAL.md")

servers:
  - url: https://api.staging.blink.sv/graphql
    description: Signet
    production: false
