#!/usr/bin/env sh

docker-compose up -d

direnv reload

. ./.envrc && \
LOGLEVEL=error jest --config ./test/jest-integration.config.js --bail --runInBand --ci --reporters=default --reporters=jest-junit
