apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 4d51b09040a3fe9ab403d4ea07464cdaf2af7979
    includePaths:
    - tasks/**/*
    - config/**/*
    - pipeline-fragments.lib.yml
