apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 69cb034648ec2597a1ba67c639079f3ef2f20acf
    includePaths:
    - tasks/**/*
    - config/**/*
    - pipeline-fragments.lib.yml
