apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 95c4fd73e3a8aa92e4b52b97e4066a1f6bdb19ab
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 95c4fd73e3a8aa92e4b52b97e4066a1f6bdb19ab
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    newRootPath: shared/ci
