apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: c15eb602081f067cec3394fa9221b333fe53b29a
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: c15eb602081f067cec3394fa9221b333fe53b29a
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    newRootPath: shared/ci
