apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 64581226f53d8bfcca1f96eec1d5e76318f859d9
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 64581226f53d8bfcca1f96eec1d5e76318f859d9
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    newRootPath: shared/ci
