apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: dcdb4978ae69e17e2d3c77d3328d3ed12afcfd62
    includePaths:
    - tasks/**/*
    - config/**/*
    - pipeline-fragments.lib.yml
