apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 21f61dd069d26270a870c870e02ad9f841e95d00
    includePaths:
    - shared/**/*
    newRootPath: shared
