apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: tasks/vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: c52118b10ec851f9cc5514bcbe84d040eb32bd9a
    includePaths:
    - tasks/**/*
    newRootPath: tasks

- path: config/vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: c52118b10ec851f9cc5514bcbe84d040eb32bd9a
    includePaths:
    - config/**/*
    newRootPath: config
