apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: f22f2cfab818a98e9449fa626a4985e2d03532fc
    includePaths:
    - shared/**/*
    newRootPath: shared
