apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: e186c637e85c89d59f52c3a7ac5a3f23b25b5331
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: e186c637e85c89d59f52c3a7ac5a3f23b25b5331
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    newRootPath: shared/ci
