apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: 8eefeec5d26ab37b59d128d3522f4563e05a2a9a
    includePaths:
    - shared/**/*
    newRootPath: shared
