export_file(
  name = "build_node_modules.py",
  visibility = ["PUBLIC"],
)

export_file(
  name = "build_npm_bin.py",
  visibility = ["PUBLIC"],
)

export_file(
  name = "prepare_build_context.py",
  visibility = ["PUBLIC"],
)

export_file(
  name = "compile_typescript.py",
  visibility = ["PUBLIC"],
)

export_file(
  name = "package_runnable_tsc_build.py",
  visibility = ["PUBLIC"],
)

export_file(
  name = "package_runnable_tsc_build_bin.py",
  visibility = ["PUBLIC"],
)
