#@ load("@ytt:data", "data")

#@ load("app-template.lib.yml",
#@   "build_edge_image",
#@   "build_edge_image_name",
#@   "app_src_resource",
#@   "app_edge_image",
#@   "bump_image_in_chart_name",
#@   "bump_image_in_chart")

#@ def consent_image():
#@   return data.values.docker_registry + "/galoy-consent"
#@ end

#@ apps = ["consent", "dashboard"]

groups:
  - name: all
    jobs:
#@ for app in apps:
    - #@ build_edge_image_name(app)
    - #@ bump_image_in_chart_name(app)
#@ end
#@ for app in apps:
  - name: #@ app
    jobs:
    - #@ build_edge_image_name(app)
    - #@ bump_image_in_chart_name(app)
#@ end

jobs:
#@ for app in apps:
  - #@ build_edge_image(app)
  - #@ bump_image_in_chart(app)
#@ end

resources:
#@ for app in apps:
  - #@ app_src_resource(app)
  - #@ app_edge_image(app)
#@ end

  - name: pipeline-tasks
    type: git
    source:
      paths: [ci/apps/*]
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key

  - name: charts-repo
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: #@ data.values.git_charts_branch
      private_key: #@ data.values.github_private_key

  - name: charts-repo-out
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: "image-bump-bot-branch"
      private_key: #@ data.values.github_private_key
