#@ load("@ytt:data", "data")

#@ load("app-template.lib.yml",
#@   "galoy_dev_image",
#@   "build_edge_image",
#@   "build_edge_image_name",
#@   "buck_test_name",
#@   "buck_test",
#@   "tilt_integration_test_name",
#@   "tilt_integration_test",
#@   "app_src_resource",
#@   "app_edge_image",
#@   "bump_image_in_chart_name",
#@   "bump_image_in_chart")

#@ apps = ["consent", "dashboard", "pay"]

groups:
  - name: all
    jobs:
#@ for app in apps:
    - #@ build_edge_image_name(app)
    - #@ buck_test_name(app)
    - #@ tilt_integration_test_name(app)
    - #@ bump_image_in_chart_name(app)
    - #@ bump_image_in_chart_name(app)
#@ end
#@ for app in apps:
  - name: #@ app
    jobs:
    - #@ build_edge_image_name(app)
    - #@ buck_test_name(app)
    - #@ tilt_integration_test_name(app)
    - #@ bump_image_in_chart_name(app)
#@ end
  - name: dev-image
    jobs:
    - build-galoy-dev-image

jobs:
#@ for app in apps:
  - #@ build_edge_image(app)
  - #@ buck_test(app)
  - #@ tilt_integration_test(app)
  - #@ bump_image_in_chart(app)
#@ end
  - name: build-galoy-dev-image
    serial: true
    plan:
      - in_parallel:
          - { get: galoy-dev-image-def, trigger: true }
      - task: build
        attempts: 2
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: nixos/nix
          inputs:
            - name: galoy-dev-image-def
              path: repo
          outputs:
            - name: repo
          run:
            path: bash
            args:
              - -c
              - |
                set -eux
                cd repo
                nix --extra-experimental-features "nix-command flakes impure-derivations ca-derivations" build .#dockerImage
                gunzip ./result -c > image.tar

      - put: galoy-dev-image
        params:
          image: repo/image.tar

resources:
#@ for app in apps:
  - #@ app_src_resource(app)
  - #@ app_edge_image(app)
#@ end

  - name: pipeline-tasks
    type: git
    source:
      paths: [ci/apps/*]
      uri: #@ data.values.git_uri
      branch: ci--add-buck-target-to-metadata
      private_key: #@ data.values.github_private_key

  - name: charts-repo
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: #@ data.values.git_charts_branch
      private_key: #@ data.values.github_private_key

  - name: charts-repo-out
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: "image-bump-bot-branch"
      private_key: #@ data.values.github_private_key

  - name: galoy-dev-image-def
    type: git
    source:
      paths: [flake.*]
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key

  - name: galoy-dev-image
    type: registry-image
    source:
      tag: latest
      username: #@ data.values.docker_registry_user
      password: #@ data.values.docker_registry_password
      repository: #@ galoy_dev_image()

  - name: nix-host
    type: pool
    source:
      uri: git@github.com:GaloyMoney/concourse-locks.git
      branch: main
      pool: docker-hosts
      private_key: #@ data.values.github_private_key
