mutation accountDisableNotificationChannel($input: AccountDisableNotificationChannelInput!) {
  accountDisableNotificationChannel(input: $input) {
    errors {
      message
    }
    account {
      notificationSettings {
        push {
          enabled
          disabledCategories
        }
      }
    }
  }
}
