mutation accountQuizCompleted($input: QuizCompletedInput!) {
  quizCompleted(input: $input) {
    quiz {
      amount
      completed
      id
    }
    errors {
      message
    }
    rewardPaid
  }
}
