query me($walletId: WalletId!, $paymentHash: PaymentHash!) {
  me {
    defaultAccount {
      id
      walletById(walletId: $walletId) {
        id
        invoiceByPaymentHash(paymentHash: $paymentHash) {
          paymentHash
          paymentStatus
          ... on LnInvoice {
            satoshis
          }
        }
      }
    }
  }
}
