mutation lnInvoicePaymentSend($input: LnInvoicePaymentInput!) {
  lnInvoicePaymentSend(input: $input) {
    errors {
      message
    }
    status
    transaction {
      initiationVia {
        ... on InitiationViaLn {
          paymentHash
          paymentRequest
        }
      }
    }
  }
}
