mutation lnInvoiceCreateOnBehalfOfRecipient(
  $input: LnInvoiceCreateOnBehalfOfRecipientInput!
) {
  lnInvoiceCreateOnBehalfOfRecipient(input: $input) {
    invoice {
      paymentRequest
      paymentHash
    }
    errors {
      message
    }
  }
}
