mutation lnNoAmountInvoiceCreate($input: LnNoAmountInvoiceCreateInput!) {
  lnNoAmountInvoiceCreate(input: $input) {
    invoice {
      paymentRequest
      paymentHash
    }
    errors {
      message
    }
  }
}
