mutation userEmailRegistrationInitiate($input: UserEmailRegistrationInitiateInput!) {
  userEmailRegistrationInitiate(input: $input) {
    errors {
      message
    }
    emailRegistrationId
    me {
      id
      email {
        address
        verified
      }
    }
  }
}
