headers:
  all:
    request:
      - propagate:
          matching: .*
include_subgraph_errors:
  all: true
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  listen: 0.0.0.0:4004
  introspection: true
  path: /graphql
cors:
  allow_any_origin: true
telemetry:
  tracing:
    otlp:
      endpoint: http://otel-agent:4318
      protocol: http
