mutation accountUpdateLevel($input: AccountUpdateLevelInput!) {
  accountUpdateLevel(input: $input) {
    errors {
      message
    }
    accountDetails {
      id
      username
      level
      status
      owner {
        id
        phone
        createdAt
      }
      wallets {
        id
        walletCurrency
        accountId
        balance
        pendingIncomingBalance
      }
      createdAt
    }
  }
}
