query filteredUserCount(
  $userIdsFilter: [ID!]
  $phoneCountryCodesFilter: [CountryCode!]
) {
  filteredUserCount(
    userIdsFilter: $userIdsFilter
    phoneCountryCodesFilter: $phoneCountryCodesFilter
  )
}
