name: "Integration test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Buck2 build
        run: |
          nix develop -c ./bats/ci_start_integration_deps.sh
      - name: Run integration tests
        run: |
          nix develop -c buck2 test //core/api:test-integration
