name: "Legacy integration test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Legacy integration test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          cd core/api/
          nix develop -c make legacy-integration-in-ci
