name: "Legacy Bats test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Legacy Bats tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v3
      - run: cd core/api && nix develop -c pnpm install --frozen-lockfile
      - name: Run bats tests
        run: |
          . ./.env && cd core/api && nix develop -c make reset-bats
