name: "Tilt CI"
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare tilt args from labels
      id: prepare_args
      run: |
        ARGS=""
        cat <<EOF > labels.json
        ${{ toJSON(github.event.pull_request.labels.*.name) }}
        EOF
        for LABEL in $(jq -r '.[]' < labels.json); do
          case "$LABEL" in
            dashboard|consent)
              ARGS+=" --test $LABEL"
              ;;
          esac
        done
        echo "Prepared args: $ARGS"
        echo "args=$ARGS" >> "$GITHUB_OUTPUT"
    - name: Tilt CI
      run: nix develop -c bash -c "cd dev && xvfb-run tilt ci -- ${{ steps.prepare_args.outputs.args }}"
