query CurrencyConversionEstimation($amount: Float!, $currency: DisplayCurrency!) {
  currencyConversionEstimation(amount: $amount, currency: $currency) {
    btcSatAmount
    id
    timestamp
    usdCentAmount
  }
}
