subscription lnInvoicePaymentStatusByHashSubscription($input: LnInvoicePaymentStatusByHashInput!) {
  lnInvoicePaymentStatusByHash(input: $input) {
    errors {
      message
    }
    status
    paymentHash
    paymentRequest
  }
}
