query myQuizQuestions {
  me {
    id
    defaultAccount {
      id
      ... on ConsumerAccount {
        quiz {
          id
          amount
          completed
          notBefore
        }
      }
    }
  }
}
