mutation ApiKeyRevoke($input: ApiKeyRevokeInput!) {
  apiKeyRevoke(input: $input) {
    apiKey {
      id
      name
      createdAt
      revoked
      expired
      lastUsedAt
      expiresAt
    }
  }
}
