mutation userEnableNotificationChannel(
  $input: UserEnableNotificationChannelInput!
) {
  userEnableNotificationChannel(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
