mutation userDisableNotificationCategory(
  $input: UserDisableNotificationCategoryInput!
) {
  userDisableNotificationCategory(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
