mutation userDisableNotificationChannel(
  $input: UserDisableNotificationChannelInput!
) {
  userDisableNotificationChannel(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
