mutation userEnableNotificationCategory(
  $input: UserEnableNotificationCategoryInput!
) {
  userEnableNotificationCategory(input: $input) {
    notificationSettings {
      push {
        enabled
        disabledCategories
      }
    }
  }
}
